### ISSUE TITLE
Browser Testing

### ISSUE THREAD

**Issue by sander-aaron** [Jowens96/animal-rescue-website#4]
FireFox Desktop - There seems to be some sort of width that is making your website lager than the actual screen size at the largest size.
I would make sure that all your images in a section have the same treatment to keep visual flow.

Chrome Android - Looks very good on mobile!

Opera Android - SAme as Chrome :)

**Comment by Jowens96** [comment]
Thanks for letting me know. I was able to get some help fixing this in class. It was a complicated and confusing process but the site seems to no longer have that extra space on it.
